version: 2
updates:
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"
